FROM eclipse-temurin:21-jre

COPY ./target/springweb-example-1.0-SNAPSHOT.jar /usr/app/springweb-example-1.0-SNAPSHOT.jar

WORKDIR /usr/app

EXPOSE 8080

CMD java -jar /usr/app/springweb-example-1.0-SNAPSHOT.jar